services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - api_crm_network
      - frontend_network

networks:
  api_crm_network:
    external: true
  frontend_network:
    external: true
