services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - api_default
      - frontend_network
networks:
  api_default:
    external: true
    name: api_default
  frontend_network:
    external: true
    name: frontend_network
