services:
  nginx:
    container_name: cleaner-app-nginx
    image: nginx:alpine
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dist:/usr/share/nginx/html
    networks:
      - api_default
      - cleaner_network

networks:
  api_default:
    external: true
    name: api_default
  cleaner_network:
    external: true
    name: cleaner_network
